spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evenly
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  liquibase:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/api/auth/google/callback
