spring:
  application:
    name: lakshmi-core
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${EVENLY_DB_USER}
    password: ${EVENLY_DB_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: never
  liquibase:
    analytics-enabled: on
    change-log: classpath:/db/changelog/db.changelog-master.xml
