spring:
  application:
    name: lakshmi-core
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${EVENLY_DB_USER}
    password: ${EVENLY_DB_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: never
  liquibase:
    analytics-enabled: on
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
        registration:
          google:
            client-name: evenly
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
evenly:
  jwt:
    auth:
      secret: ${EVENLY_JWT_AUTH_SECRET}
      issuer: evenly
      expiration: 86400
    state:
      secret: ${EVENLY_JWT_STATE_SECRET}
      issuer: evenly-oauth
      expiration: 300
